import "../styles/globals.css";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { StoreProvider } from "./StoreProvider";

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Hima",
};

interface Props {
  readonly children: ReactNode;
}

export default function RootLayout({ children }: Props) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="flex max-h-dvh h-dvh overflow-hidden">{children}</body>
      </html>
    </StoreProvider>
  );
}
